#include "codegen.h"
#include <stdarg.h>
#include <stdio.h>

extern FILE* __src_file;

/******************************************************************************/
void cgen_box_body( int ident, const char* box_name )
{
    cgen_ident( ident );
    cgen_print( "return START_ROUTINE_NET( handler, %s );\n",
            box_name );
}

/******************************************************************************/
void cgen_box_enum_head( int ident, const char* name, const char* mode )
{
    cgen_ident( ident );
    cgen_print( "enum net_%s_%s_e\n{\n", name, mode );
}

/******************************************************************************/
void cgen_box_enum_tail( int ident )
{
    cgen_ident( ident );
    cgen_print( "};\n" );
}

/******************************************************************************/
void cgen_box_fct_ext( int ident, const char* name )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_EXTERN( %s );\n", name );
}

/******************************************************************************/
void cgen_box_fct_head( int ident, const char* name )
{
    cgen_ident( ident );
    cgen_print( "void* start_routine_%s( void* handler )\n", name );
}

/******************************************************************************/
void cgen_box_fct_proto( int ident, const char* name )
{
    cgen_ident( ident );
    cgen_print( "void* start_routine_%s( void* );\n", name );
}

/******************************************************************************/
void cgen_box_port( int ident, const char* box_name, const char* port_name,
        const char* mode )
{
    cgen_ident( ident );
    cgen_print( "SMX_PORT_IDX_%s_%s_%s,\n", box_name, mode, port_name );
}

/******************************************************************************/
void cgen_channel_create( int ident, int id, int dsrc, int ddst, int len,
        const char* name )
{
    cgen_ident( ident );
    cgen_print( "SMX_CHANNEL_CREATE( %d, %d, ", id, len );
    if( dsrc && ddst )
        cgen_print( "SMX_D_FIFO_D" );
    else if( dsrc )
        cgen_print( "SMX_D_FIFO" );
    else if( ddst )
        cgen_print( "SMX_FIFO_D" );
    else
        cgen_print( "SMX_FIFO" );
    cgen_print( ", %s );\n", name );
}

/******************************************************************************/
void cgen_channel_destroy( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_CHANNEL_DESTROY( %d );\n", id );
}

/******************************************************************************/
void cgen_connect( int ident, int id_ch, int id_box, const char* box_name,
        const char* ch_name, const char* mode, int is_sync )
{
    if( is_sync )
    {
        cgen_ident( ident );
        cgen_print( "SMX_CONNECT_ARR( %d, %d, %s );\n", id_box,
                id_ch, mode );
    }
    else {
        cgen_ident( ident );
        cgen_print( "SMX_CONNECT( %d, %d, %s, %s, %s );\n", id_box,
                id_ch, box_name, ch_name, mode );
    }
}

/******************************************************************************/
void cgen_connect_rn( int ident, int id_ch, int id_box )
{
    cgen_ident( ident );
    cgen_print( "SMX_CONNECT_RN( %d, %d );\n", id_box, id_ch );
}

/******************************************************************************/
void cgen_connect_guard( int ident, int id_ch, int iats, int iatns )
{
    cgen_ident( ident );
    cgen_print( "SMX_CONNECT_GUARD( %d, %d, %d );\n", id_ch, iats, iatns );
}

/******************************************************************************/
void cgen_connect_tf( int ident, int vid, int eid1, int eid2,
        const char* ch_name )
{
    cgen_ident( ident );
    cgen_print( "SMX_CONNECT_TF( %d, %d, %d, %s );\n", vid, eid1,
            eid2, ch_name );
}

/******************************************************************************/
void cgen_endif( const char* name )
{
    cgen_print( "#endif // %s\n", name );
}

/******************************************************************************/
void cgen_block_end( int ident )
{
    cgen_ident( ident );
    cgen_print( "}\n\n" );
}

/******************************************************************************/
void cgen_block_start( int ident )
{
    cgen_ident( ident );
    cgen_print( "{\n" );
}

/******************************************************************************/
void cgen_header_c_file( const char* name )
{
  cgen_print( "/**\n" );
  cgen_print( " * @file %s.h\n", name );
  cgen_print( " *\n" );
  cgen_print( " * Source code of compiled streamix-file for runtime.\n" );
  cgen_print( " *\n" );
  cgen_print( " * THIS FILE HAS BEEN GENERATED.\n" );
  cgen_print( " * DO NOT EDIT THIS FILE.\n" );
  cgen_print( " * EDIT THE ORIGINAL STREAMIX-SOURCE FILE %s.smx INSTEAD!\n",
          name );
  cgen_print( " *\n" );
  cgen_print( " * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!\n" );
  cgen_print( " */\n\n" );
}

/******************************************************************************/
void cgen_header_h_file( const char* name )
{
  cgen_print( "/**\n" );
  cgen_print( " * @file %s.c\n", name );
  cgen_print( " *\n" );
  cgen_print( " * Header definitions of compiled streamix-file for "
          "runtime.\n" );
  cgen_print( " *\n" );
  cgen_print( " * THIS FILE HAS BEEN GENERATED.\n" );
  cgen_print( " * DO NOT EDIT THIS FILE.\n" );
  cgen_print( " * EDIT THE ORIGINAL STREAMIX-SOURCE FILE %s.smx INSTEAD!\n",
          name );
  cgen_print( " *\n" );
  cgen_print( " * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!\n" );
  cgen_print( " */\n\n" );
}

/******************************************************************************/
void cgen_ident( int ident )
{
    int i;
    for( i = 0; i < ident; i++ ) cgen_print( "    " );
}

/******************************************************************************/
void cgen_ifndef( const char* name )
{
    cgen_print( "#ifndef %s\n", name );
    cgen_print( "#define %s\n\n", name );
}

/******************************************************************************/
void cgen_include( const char* file )
{
    cgen_print( "#include <%s.h>\n", file );
}

/******************************************************************************/
void cgen_include_local( const char* file )
{
    cgen_print( "#include \"%s.h\"\n", file );
}

/******************************************************************************/
void cgen_main_head()
{
    cgen_print( "int main( void )\n" );
}

/******************************************************************************/
void cgen_net_init( int ident, int id, int indegree, int outdegree )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_INIT( %d, %d, %d );\n", id, indegree,
            outdegree );
}

/******************************************************************************/
void cgen_net_init_profiler( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_INIT_PROFILER( %d );\n", id );
}

/******************************************************************************/
void cgen_net_init_rn( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_INIT_RN( %d );\n", id );
}

/******************************************************************************/
void cgen_net_init_tf( int ident, int id, int sec, int nsec )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_INIT_TF( %d, %d, %d );\n", id, sec, nsec );
}

/******************************************************************************/
void cgen_net_create( int ident, int id, const char* net_name,
        const char* box_name )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_CREATE( %d, %s, %s );\n", id, net_name, box_name );
}

/******************************************************************************/
void cgen_net_destroy( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_DESTROY( %d );\n", id );
}

/******************************************************************************/
void cgen_net_destroy_profiler( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_DESTROY_PROFILER( %d );\n", id );
}

/******************************************************************************/
void cgen_net_destroy_rn( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_DESTROY_RN( %d );\n", id );
}

/******************************************************************************/
void cgen_net_destroy_tf( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_DESTROY_TF( %d );\n", id );
}

/******************************************************************************/
void cgen_net_finalize_profiler( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_FINALIZE_PROFILER( %d );\n", id );
}

/******************************************************************************/
void cgen_net_finalize_tf( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_FINALIZE_TF( %d );\n", id );
}

/******************************************************************************/
void cgen_net_run( int ident, int id, const char* box_name, int prio )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_RUN( %d, %s, %d );\n", id, box_name,
            prio );
}

/******************************************************************************/
void cgen_net_tt( int ident )
{
    cgen_ident( ident );
    cgen_print( "smx_timer_t* timer;\n" );
}

/******************************************************************************/
void cgen_net_wait_end( int ident, int id )
{
    cgen_ident( ident );
    cgen_print( "SMX_NET_WAIT_END( %d );\n", id );
}

/******************************************************************************/
int cgen_print( const char* format, ... )
{
    int res;
    va_list args;
    va_start( args, format );
    res = vfprintf( __src_file, format, args );
    va_end( args );
    return res;
}

/******************************************************************************/
void cgen_program_init( int ident )
{
    cgen_ident( ident );
    cgen_print( "SMX_PROGRAM_INIT();\n" );
}

/******************************************************************************/
void cgen_program_init_run( int ident )
{
    cgen_ident( ident );
    cgen_print( "SMX_PROGRAM_INIT_RUN();\n" );
}

/******************************************************************************/
void cgen_program_cleanup( int ident )
{
    cgen_ident( ident );
    cgen_print( "SMX_PROGRAM_CLEANUP();\n" );
}

/******************************************************************************/
void cgen_struct_head( int ident )
{
    cgen_ident( ident );
    cgen_print( "struct {\n" );
}

/******************************************************************************/
void cgen_struct_tail( int ident, const char* mode )
{
    cgen_ident( ident );
    cgen_print( "} %s;\n", mode );
}
